### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by Hombre2014**
In this phase the project setup have been completed.
- Set up React app
- Install React related linters
- Using Gitflow

### CODE REVIEW

**Review by hiromataba — CHANGES_REQUESTED** [review]
Hi @Hombre2014   :wave: , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight :champagne:  :heavy_check_mark: 
- No linter errors :heavy_check_mark: 
- You did great using `CRA` to create your application :heavy_check_mark:
- Nice PR title and description :heavy_check_mark:  

## Required Changes ♻️

- [ ] Please remove the icons and images in your public directory since you are not going to need them to make your project clean

- [ ] Kindly update your README file by adding the command to install npm in your available script, `npm install`

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] [OPTIONAL] You have a nice README file but I think for this project you do not need this learn more section :point_down: : 
image

and this :point_down: 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Hombre2014** [comment]
Thanks for your fast review.

**Comment by Hombre2014** [comment]
All the recommended and suggested changes have been implemented in this PR.
- Add `npm install` in README file
- Removed the unnecessary icons and images from `public` folder
- Remove Learn more and Getting started sections from README file

**Review by elyor-doniyorov — APPROVED** [review]
Hi @Hombre2014, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
